services:
  api:
    container_name: ai4infra-bitwarden-api
    user: "1001:1001"
    networks:
      - default
      - ai4infra
  
  web:
    container_name: ai4infra-bitwarden-web
    user: "1001:1001"
    networks:
      - default
      - ai4infra
  
  admin:
    container_name: ai4infra-bitwarden-admin
    user: "1001:1001"
    networks:
      - default
      - ai4infra
  
  identity:
    container_name: ai4infra-bitwarden-identity
    user: "1001:1001"
    networks:
      - default
      - ai4infra
  
  sso:
    container_name: ai4infra-bitwarden-sso
    user: "1001:1001"
    networks:
      - default
      - ai4infra
  
  events:
    container_name: ai4infra-bitwarden-events
    user: "1001:1001"
    networks:
      - default
      - ai4infra
  
  notifications:
    container_name: ai4infra-bitwarden-notifications
    user: "1001:1001"
    networks:
      - default
      - ai4infra
  
  attachments:
    container_name: ai4infra-bitwarden-attachments
    user: "1001:1001"
    networks:
      - default
      - ai4infra
  
  nginx:
    container_name: ai4infra-bitwarden-nginx
    networks:
      - default
      - ai4infra
  
  mssql:
    container_name: ai4infra-bitwarden-mssql
    networks:
      - default
      - ai4infra
  
  icons:
    container_name: ai4infra-bitwarden-icons
    networks:
      - default
      - ai4infra

networks:
  ai4infra:
    external: true
    name: ai4infra