###############################################
# 파일명: config/bitwarden.yml
# 목적: Bitwarden 서비스 설정
# 내용:
#   - TLS 인증서 경로/권한
#   - bwdata 마운트 폴더 권한
#   - UID/GID 및 파일모드 일관 관리
# 변경이력:
#   - 2025-11-22: 최초 작성 (BenKorea)
###############################################

service:
  enable: true

permissions:
  uid: 1001
  gid: 1001

  # bwdata/** 아래 권한
  data_dir_mode: "700"

  # SSL 폴더의 key/cert default permission
  key_mode: "600"
  cert_mode: "644"

bitwarden:
  domain: "bitwarden.ai4infra.internal"
