###############################################
# 파일명: config/bitwarden.yml
# 목적: Bitwarden 서비스 설정
# 내용:
#   - TLS 인증서 경로/권한
#   - bwdata 마운트 폴더 권한
#   - UID/GID 및 파일모드 일관 관리
# 변경이력:
#   - 2025-11-22: 최초 작성 (BenKorea)
###############################################

service:
  enable: true

path:
  data: ${BASE_DIR}/bitwarden/bwdata  
  private_key: ${BASE_DIR}/bitwarden/bwdata/ssl/${BITWARDEN_DOMAIN}/private.key
  service_crt: ${BASE_DIR}/bitwarden/bwdata/ssl/${BITWARDEN_DOMAIN}/certificate.crt

permissions:
  uid: 1001
  gid: 1001
  data_dir_mode: "700"
  key_mode: "600"
  cert_mode: "644"
