####################################
# 파일명: config/bitwarden.yml
# 목적: BBitwarden 설정
# 기능: 
#  - config/bitwarden.yml 파일이 존재하지 않으면 오류가 발생하므로 생성함
# 변경이력
#  - 2025-11-01 최초 구현 (BenKorea)
#####################################
bitwardens:
  BW_DATA_DIR: ${BASE_DIR}/bwdata                   # 데이터 디렉토리
