service:
  enable: true

path:
  directories:
    data: "${BASE_DIR}/ldap/data"
    config: "${BASE_DIR}/ldap/config"
    certs: "${BASE_DIR}/ldap/certs"

env_vars:
  LDAP_ORGANISATION: "AI4Infra Hospital"
  LDAP_DOMAIN: "ai4infra.internal"
  LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}" # injected from .env
