####################################
# 파일명: config/ldap.yml
# 목적: OpenLDAP 설정
# 기능: 
#  - LDAP 디렉터리 서비스 설정
#  - 사용자 인증 및 권한 관리
# 변경이력
#  - 2025-11-22: permission 추가 (BenKorea)
#  - 2025-10-08: 최초 구현 (BenKorea)
#####################################

permissions:
  uid: 100
  gid: 101
  data_dir_mode: "700"
  key_mode: "600"
  cert_mode: "644"

LDAP_DATA_DIR: "${BASE_DIR}/ldap/data"
LDAP_CONFIG_DIR: ${BASE_DIR}/ldap/config                       # 설정 파일 경로
LDAP_PORT: 389                                                 # LDAP 포트
LDAP_SSL_PORT: 636                                            # LDAP SSL 포트
