####################################
# 파일명: config/ldap.yml
# 목적: OpenLDAP 설정
# 기능: 
#  - LDAP 디렉터리 서비스 설정
#  - 사용자 인증 및 권한 관리
# 변경이력
#  - 2025-11-22: permission 추가 (BenKorea)
#  - 2025-10-08: 최초 구현 (BenKorea)
#####################################

service:
  enable: true

path:
  data: ${BASE_DIR}/ladp/data
  config: ${BASE_DIR}/ldap/config/postgresql.conf
  private_key: ${BASE_DIR}/ldap/certs/private.key
  service_crt: ${BASE_DIR}/ldap/certs/certificate.crt
  root_ca: ${BASE_DIR}/ldap/certs/rootCA.crt  

permissions:
  uid: 100
  gid: 101
  data_dir_mode: "700"
  key_mode: "600"
  cert_mode: "644"

env_vars:                  
  LDAP_PORT: 389
  LDAP_SSL_PORT: 636
