tls:
  use_external_ca: false

  # 외부 CA 사용 시 설정
  external_ca_cert: ""      # 예: /opt/ai4infra/external_ca/ca.pem
  external_ca_key: ""       # 필요 시 (대부분 제공되지 않음)
  service_cert: ""          # 외부에서 발급된 server.crt
  service_key: ""           # 외부에서 발급된 private.key

  # 내부 CA 사용 시 설정
  internal_root_ca_cert: "${BASE_DIR}/certs/ca/rootCA.pem"
  internal_root_ca_key:  "${BASE_DIR}/certs/ca/rootCA.key"