####################################
# 파일명: config/vault.yml
# 목적: HashiCorp Vault 설정
# 기능: 
#  - 보안 시크릿 관리 서비스 설정
#  - 인증서 및 키 관리
# 변경이력
#  - 2025-10-06: 최초 구현 (BenKorea)
#####################################

VAULT_FILE_DIR: ${BASE_DIR}/vault/file   
VAULT_CERTS_DIR: ${BASE_DIR}/vault/certs                      # 인증서 디렉토리
VAULT_CONFIG_DIR: ${BASE_DIR}/vault/config                      # 설정 파일 경로
VAULT_PORT: 8200                                                # Vault 포트
 
