version: "3.9"

services:
  postgres:
    command:
      - "postgres"
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/var/lib/postgresql/data/certs/certificate.crt"
      - "-c"
      - "ssl_key_file=/var/lib/postgresql/data/certs/private.key"
      - "-c"
      - "ssl_ca_file=/var/lib/postgresql/data/certs/rootCA.crt"

    volumes:
      # PostgreSQL 데이터 디렉터리 (Override하지 않으면 docker-compose.yml의 설정이 유지되지만 명시적으로 적음)
      - /opt/ai4infra/postgres/data:/var/lib/postgresql/data

      # [SEC-07] mTLS Enforcement Configs
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./config/pg_ident.conf:/var/lib/postgresql/data/pg_ident.conf

      # [SEC-07] Certs Mount (for ssl_cert_file, etc)
      - ./certs:/var/lib/postgresql/data/certs
